### ISSUE TITLE
Add Daemonsets

### ISSUE THREAD

**Issue by Spazzy757** [Spazzy757/ephemeral-enforcer#6]
**Is your feature request related to a problem? Please describe.**
The current Setup will delete Deployments, services, configmaps, secrets and statefulsets. I would like to add Daemonsets to that list

**Describe the solution you'd like**
Add a section in the `workloadkiller.go` to enable it

**Additional context**
This should just be a simple COPY and paste as far as I can see

**Comment by meggieveggie** [comment]
I would like to work on this issue

**Comment by Spazzy757** [comment]
Thanks @meggieveggie
