### ISSUE TITLE
Distroless Image

### ISSUE THREAD

**Issue by Spazzy757** [Spazzy757/ephemeral-enforcer#8]
**Is your feature request related to a problem? Please describe.**
Currently I am using Alpine, This is a small image but not the smallest it could possibly be

**Describe the solution you'd like**
Changes the Final Docker IMage to be based on distroless or scratch

**Comment by meggieveggie** [comment]
Working on it

**Comment by Spazzy757** [comment]
Thanks @meggieveggie
